workflows:
  android-workflow:
    name: Android Build
    instance_type: linux
    max_build_duration: 120
    scripts:
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
